firstColumn: "№ з/п"
secondColumn: "Кому видано"
thirdColumn: "Підрозділ"
fourthColumn: "Обліковий\nномер"
fifthColumn: "Кількість\nаркушів"
sixthColumn: "Дата\nотримання"
seventhColumn: "Підпис про\nотримання"
eighthColumn: "Підпис про\nзворотний\nприйом, дата"